package Models.Question;

public enum TypeEnfant {
    STRUCTURE_FAMILIALE,
    DYNAMIQUE_ENFANT,
    ANTECEDENTS_FAMILIAUX,
    CONDITIONS_NATALES,
    DEVELOPPEMENT_PSYCHOMOTEUR,
    DEVELOPPEMENT_LANGAGIER,
    CARACTERE_ET_COMPORTEMENT,
}
